### ISSUE TITLE
Crash when visit github

### ISSUE THREAD

**Issue by epirus** [emacs-eaf/emacs-application-framework#1016]
![iShot_2022-10-03_下午6 24 25](https://user-images.githubusercontent.com/2031281/193555734-aa16e91f-4c51-48ae-89bd-8d784a4148a6.jpg)

Environment:

    M1 Macbook
    python3.9
    Qt6

Just submit my error information

**Comment by manateelazycat** [comment]
Are you use evil-mode?

**Comment by epirus** [comment]
> Are you use evil-mode?

nope

**Comment by epirus** [comment]
> 

other website is nomal and just open github for a moment and then crash

**Comment by manateelazycat** [comment]
M1 can't use gdb to debug, you need add print code in browser/buffer.py to tell me which function cause crash, thanks.

**Comment by manateelazycat** [comment]
It's a bug of PyQt6 6.4.0 , has fixed in https://github.com/emacs-eaf/emacs-application-framework/commit/c596cdd624a3aaaaf3ce9936be839ece42c9acfb

You need do below command to fix this issue:
`
pip3 uninstall PyQt6 PyQt6-Qt6 PyQt6-WebEngine PyQt6-WebEngine-Qt6   
pip3 install PyQt6==6.3.1 PyQt6-Qt6==6.3.1 PyQt6-WebEngine==6.3.1 PyQt6-WebEngine-Qt6==6.3.1
`

Thanks for report.
