### ISSUE TITLE
macOS: EAF buffers always stay on top of other applications

### ISSUE THREAD

**Issue by taquangtrung** [emacs-eaf/emacs-application-framework#835]
Hi,

**Describe the bug**

When I'm opening an EAF webpage and then press Alt-Tab to switch to another application, the EAF webpage always stays on top of the new application.

**To Reproduce**

- Open Google Chrome
- Open Emacs and run `eaf-search-it` to open a webpage.
- Press Alt-Tab to switch to Google Chrome, the EAF webpage always stays on top of Google Chrome.

<img width="1680" alt="Screenshot 2021-08-27 at 9 04 33 AM" src="https://user-images.githubusercontent.com/193967/131056460-0f2287ba-dca1-4df2-962c-b2afa7354466.png">

**Expected behavior**

After switching to Google Chrome, the EAF webpage should stay below it.

**Versions (please complete the following info):**
 - Distro and DE/WM: macOS BigSur 11.3
 - Versions of Dependencies: eaf-20210826.100
 - M-x emacs-version: 27.2

**Comment by Gira-X** [comment]
First of all, the macOS EAF buffers are already correctly hidden with a temporary buffer, but I felt that alt-tabbing feels sluggish with them, so I tried to improve it.

Here is a video how it currently behaves on the latest `master`:

https://user-images.githubusercontent.com/15002298/146686921-3c7b0623-13f6-4c3c-92d4-5d527f4395a9.mov

The current `(eaf--mac-focus-change)` is rather slow because it uses `(shell-command-to-string "app-frontmost --name")` twice and has this workaround with the `*eaf-temp*` buffer which I feel is not that nice.

> is it possible to add a hook to remove the attribute Qt.WindowStaysOnTopHint from eaf-browser when Emacs loses focus, and add the attribute back when Emacs gains focus?

This sounds like a great idea and I managed to implement it with surprisingly good results in my limited testing (on macOS 10.14.6) without relying on the temporary `*eaf-temp*` buffer.
I also only use a single Emacs instance at all times with a single frame where it seems to work well.

# Added functions in eaf.py

```python
    @PostGui()
    def handle_emacs_focus_in(self):
        for key in list(self.view_dict):
            self.view_dict[key].handle_emacs_focus_in()

    @PostGui()
    def handle_emacs_focus_out(self):
        for key in list(self.view_dict):
            self.view_dict[key].handle_emacs_focus_out()
```

# Added functions in view.py

```python
    def handle_emacs_focus_in(self):
        self.setWindowFlag(Qt.WindowStaysOnTopHint, True)
        self.show()

    def handle_emacs_focus_out(self):
        self.setWindowFlag(Qt.WindowStaysOnTopHint, False)
        self.hide()
```

# Emacs Lisp

```emacs-lisp
(defvar dima-focus-out-auto-save-timer nil
  "Use timer to ignore spurious focus events.

See
https://old.reddit.com/r/emacs/comments/\
kxsgtn/ignore_spurious_focus_events_for/")

(defun dima-eaf-mac-focus-in ()
  (eaf-call-async "handle_emacs_focus_in")
  (set-window-configuration
   (frame-parameter (selected-frame) 'eaf--mac-frame)))

(defun dima-eaf-mac-focus-out ()
  (eaf-call-async "handle_emacs_focus_out")
  (set-frame-parameter (selected-frame) 'eaf--mac-frame
                       (current-window-configuration)))

(defun dima-eaf-mac-focus-change-handler ()
  ;; ignore errors related to
  ;; (wrong-type-argument eaf-epc-manager nil)
  (ignore-errors
    (if (frame-focus-state)
        (dima-eaf-mac-focus-in)
      (dima-eaf-mac-focus-out)))
  (setq dima-focus-out-auto-save-timer nil))

(defun dima-eaf-mac-after-focus-change ()
  (setq dima-focus-out-auto-save-timer
        (unless dima-focus-out-auto-save-timer
          (run-at-time 0.06 nil #'dima-eaf-mac-focus-change-handler))))
```

I am a bit reluctant to create a MR because I am not too sure if it might still have some side-effects because my `(dima-eaf-mac-focus-change-handler)` is a lot simpler.

@taquangtrung maybe you would like to test this?

---

With the above code alt-tabbing feels almost instantaneous and on focusing inside Emacs, the correct EAF buffer is also still selected:

https://user-images.githubusercontent.com/15002298/146686961-a65e9d34-ca3f-46de-878f-be4fad8cd6c8.mov

**Comment by Gira-X** [comment]
Oops, I forget to copy and paste in the Emacs Lisp setup code. Now it is there!

**Comment by manateelazycat** [comment]
> Oops, I forget to copy and paste in the Emacs Lisp setup code. Now it is there!

can you give a patch for macOS platform?

thanks

**Comment by Gira-X** [comment]
I opened a pull request: https://github.com/emacs-eaf/emacs-application-framework/pull/894
