### ISSUE TITLE
bug / missing "feature": tags for versions

### ISSUE THREAD

**Issue by xgqt** [emacs-eaf/emacs-application-framework#964]
I noticed version inside EAF says:

> ;; Version: 0.5

But no releases/tags are in the git repository.

Cloud this and other Emacs-EAF repos tag their releases? 
This would make packagers (and to some extent user's) work easier.

Thanks in advance!

**Comment by manateelazycat** [comment]
EAF has too many applications, and the application depends on EAF core API, My time is limited, and I don’t have so much time to maintain different tags. Please use the latest version. If you have any questions, please give feedback.

Thanks for your suggestions.

**Comment by xgqt** [comment]
@manateelazycat 

> EAF has too many applications, and the application depends on EAF core API,

If I understand correctly the apps are already decoupled from main repository so this is not really a problem if you had to keep tagging only the core repo (this one).

> I don’t have so much time to maintain different tags. 

I'm NOT taking about full-maintenance branches nor LTS releases (like the qt5 branch). 
I'm talking about having a definitive "release"-like point in the repo.

> Please use the latest version.

Always using HEAD can get confusing and messy.

**Comment by manateelazycat** [comment]
I will refactory code of EAF core APIs, even ten versions in one day, and EAF application depend on special EAF core version, otherwise EAF application will crash! (Such as, this patch https://github.com/emacs-eaf/emacs-application-framework/commit/743ae2eebe94e5739fa5ed1d0081b4b0957bd048)

If I tag EAF core, I need tag every EAF application with same version, and I need change install-eaf.py to support those tag version.

EAF's feature is stable, but API is not stable enough, add tag will waste too much time.

**Comment by xgqt** [comment]
I see, thanks fro clarification!

**Comment by MatthewZMD** [comment]
That's correct, I've thought about adding tags many times, but never got to the point of adding it for real. We don't want to add tags for the sake of adding tags.
